Add destructor to JuliaGcsClient
Avoids this failure when `JuliaGcsClient` is garbage collected:

```
libc++abi: terminating due to uncaught exception of type std::runtime_error: GCS client not initialized; did you forget to Connect?

[13612] signal (6): Abort trap: 6
in expression starting at /Users/cvogt/.julia/dev/Ray/test/runtests.jl:19
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 30955062 (Pool: 30929299; Big: 25763); GC: 43
ERROR: Package Ray errored during testing (received signal: 6)
```