Use GCSClient instead of PythonGCSClient (#211)
* Use GCSClient instead of PythonGCSClient

* delete .vscode settings

* Delete tests that no longer apply

* Delete timedwait_for_function

* add back test

* add back function manager tests

* formatting

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* add comments with links to src code

* add finalizer to FunctionManager

* add Connect-do syntax

* connect to GCSClient in FunctionManager constructor

* Revert "connect to GCSClient in FunctionManager constructor"

This reverts commit 7769d88669a622dafa8c3bbab4e057a79d35b403.

* return body()

* call check_status

* add finalizer call in _init_global_function_manager

* Disconnect from unconnected client should no-op

* Apply suggestions from code review

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* call finalizer before check_status

Co-authored-by: Curtis Vogt <curtis.vogt@gmail.com>

* delete finalizer from the FunctionManager constructor

Co-authored-by: Curtis Vogt <curtis.vogt@gmail.com>

* function manager needs to be mutable

* Add destructor to JuliaGcsClient

Avoids this failure when `JuliaGcsClient` is garbage collected:

```
libc++abi: terminating due to uncaught exception of type std::runtime_error: GCS client not initialized; did you forget to Connect?

[13612] signal (6): Abort trap: 6
in expression starting at /Users/cvogt/.julia/dev/Ray/test/runtests.jl:19
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 30955062 (Pool: 30929299; Big: 25763); GC: 43
ERROR: Package Ray errored during testing (received signal: 6)
```

* Disconnect GCS client in function manager tests

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Curtis Vogt <curtis.vogt@gmail.com>